# config for training

trainer:
  checkpoint: "./tune/2spk_pit_a"
  optimizer: "adam"
  # 1e-3 => str
  # 1.0e-3 => float
  lr: 1.0e-3
  momentum: 0.8
  weight_decay: 0
  clip_norm: 200
  min_lr: 1.0e-10
  patience: 1
  factor: 0.7

model:
  num_spks: 2
  rnn: "lstm"
  num_layers: 3
  hidden_size: 1792
  dropout: 0.5
  non_linear: "relu"
  bidirectional: false

spectrogram_reader:
  frame_shift: 128
  frame_length: 256
  window: "hann"
  transpose: true
  # NOTE: do not apply log here
  # false => produce psm
  # true  => produce irm
  apply_abs: false

train_scp_conf:
  mixture: "C:/Users/Kalle/Desktop/kandi/LibriSpeech/train-clean-100/mix.scp"
  spk1: "C:/Users/Kalle/Desktop/kandi/LibriSpeech/train-clean-100/spk1.scp"
  spk2: "C:/Users/Kalle/Desktop/kandi/LibriSpeech/train-clean-100/spk2.scp"

valid_scp_conf:
  mixture: "C:/Users/Kalle/Desktop/kandi/LibriSpeech/dev/mix.scp"
  spk1: "C:/Users/Kalle/Desktop/kandi/LibriSpeech/dev/spk1.scp"
  spk2: "C:/Users/Kalle/Desktop/kandi/LibriSpeech/dev/spk2.scp"

debug_scp_conf:
  mixture: "C:/Users/Kalle/Desktop/kandi/LibriSpeech/test/mix.scp"
  spk1: "C:/Users/Kalle/Desktop/kandi/LibriSpeech/test/spk1.scp"
  spk2: "C:/Users/Kalle/Desktop/kandi/LibriSpeech/test/spk2.scp"

dataloader:
  shuffle: true
  batch_size: 4
  drop_last: false
  apply_log: true
  mvn_dict: false

